package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * BankDetails generated by hbm2java
 */
@Entity
@Table(name = "bank_details", catalog = "huddil")
public class BankDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9111730558941353154L;
	private int userId;
	private UserPref userPref;
	private String bankName;
	private int accountNo;
	private int ifscCode;
	private String branchName;
	private String nameAsInBank;

	public BankDetails() {
	}

	public BankDetails(UserPref userPref, String bankName, int accountNo, int ifscCode, String branchName,
			String nameAsInBank) {
		this.userPref = userPref;
		this.bankName = bankName;
		this.accountNo = accountNo;
		this.ifscCode = ifscCode;
		this.branchName = branchName;
		this.nameAsInBank = nameAsInBank;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "userPref"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public UserPref getUserPref() {
		return this.userPref;
	}

	public void setUserPref(UserPref userPref) {
		this.userPref = userPref;
	}

	@Column(name = "bankName", nullable = false, length = 128)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "accountNo", nullable = false)
	public int getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(int accountNo) {
		this.accountNo = accountNo;
	}

	@Column(name = "ifscCode", nullable = false)
	public int getIfscCode() {
		return this.ifscCode;
	}

	public void setIfscCode(int ifscCode) {
		this.ifscCode = ifscCode;
	}

	@Column(name = "branchName", nullable = false, length = 45)
	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	@Column(name = "nameAsInBank", nullable = false, length = 45)
	public String getNameAsInBank() {
		return this.nameAsInBank;
	}

	public void setNameAsInBank(String nameAsInBank) {
		this.nameAsInBank = nameAsInBank;
	}

}
