package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Cancellation generated by hbm2java
 */
@SqlResultSetMapping(name = "cancellationMailData", classes = {
		@ConstructorResult(targetClass = CancellationNotificationTemplate.class, columns = {
				@ColumnResult(name = "spName"), @ColumnResult(name = "spEmailId"), @ColumnResult(name = "spMobileNo"),
				@ColumnResult(name = "spMobileVerified"), @ColumnResult(name = "cName"),
				@ColumnResult(name = "cEmailId"), @ColumnResult(name = "cMobileNo"),
				@ColumnResult(name = "cMobileVerified"), @ColumnResult(name = "duration1"),
				@ColumnResult(name = "percentage1"), @ColumnResult(name = "duration2"),
				@ColumnResult(name = "percentage2"), @ColumnResult(name = "duration3"),
				@ColumnResult(name = "percentage3"), @ColumnResult(name = "bookingId"),
				@ColumnResult(name = "fromTime"), @ColumnResult(name = "paymentId"), @ColumnResult(name = "totalPrice"),
				@ColumnResult(name = "cityName") }) })

@Entity
@Table(name = "cancellation", catalog = "huddil")
public class Cancellation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6904587369787413819L;
	private Integer id;
	private Facility facility;
	private UserPref userPrefByBookedUserId;
	private UserPref userPrefByCancelledUserId;
	private Date bookedFrom;
	private Date bookedTo;
	private Date bookedTime;
	private Integer seats;
	private double price;
	private double totalPrice;
	private double refundAmount;
	private String paymentId;
	private String refundId;
	private String paymentMethod;
	private int cancellationPolicyId;
	private Date cancelledDateTime;
	private int bookingId;
	private int bookedStatus;
	private Date approvedTime;

	public Cancellation() {
	}

	public Cancellation(Facility facility, UserPref userPrefByBookedUserId, UserPref userPrefByCancelledUserId,
			Date bookedFrom, Date bookedTo, Date bookedTime, double price, double totalPrice, double refundAmount,
			String paymentMethod, int cancellationPolicyId, Date cancelledDateTime, int bookingId, int bookedStatus) {
		this.facility = facility;
		this.userPrefByBookedUserId = userPrefByBookedUserId;
		this.userPrefByCancelledUserId = userPrefByCancelledUserId;
		this.bookedFrom = bookedFrom;
		this.bookedTo = bookedTo;
		this.bookedTime = bookedTime;
		this.price = price;
		this.totalPrice = totalPrice;
		this.refundAmount = refundAmount;
		this.paymentMethod = paymentMethod;
		this.cancellationPolicyId = cancellationPolicyId;
		this.cancelledDateTime = cancelledDateTime;
		this.bookingId = bookingId;
		this.bookedStatus = bookedStatus;
	}

	public Cancellation(Facility facility, UserPref userPrefByBookedUserId, UserPref userPrefByCancelledUserId,
			Date bookedFrom, Date bookedTo, Date bookedTime, Integer seats, double price, double totalPrice,
			double refundAmount, String paymentId, String refundId, String paymentMethod, int cancellationPolicyId,
			Date cancelledDateTime, int bookingId, int bookedStatus, Date approvedTime) {
		this.facility = facility;
		this.userPrefByBookedUserId = userPrefByBookedUserId;
		this.userPrefByCancelledUserId = userPrefByCancelledUserId;
		this.bookedFrom = bookedFrom;
		this.bookedTo = bookedTo;
		this.bookedTime = bookedTime;
		this.seats = seats;
		this.price = price;
		this.totalPrice = totalPrice;
		this.refundAmount = refundAmount;
		this.paymentId = paymentId;
		this.refundId = refundId;
		this.paymentMethod = paymentMethod;
		this.cancellationPolicyId = cancellationPolicyId;
		this.cancelledDateTime = cancelledDateTime;
		this.bookingId = bookingId;
		this.bookedStatus = bookedStatus;
		this.approvedTime = approvedTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "facilityId", nullable = false)
	@JsonIgnore
	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bookedUserId", nullable = false)
	public UserPref getUserPrefByBookedUserId() {
		return this.userPrefByBookedUserId;
	}

	public void setUserPrefByBookedUserId(UserPref userPrefByBookedUserId) {
		this.userPrefByBookedUserId = userPrefByBookedUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cancelledUserId", nullable = false)
	public UserPref getUserPrefByCancelledUserId() {
		return this.userPrefByCancelledUserId;
	}

	public void setUserPrefByCancelledUserId(UserPref userPrefByCancelledUserId) {
		this.userPrefByCancelledUserId = userPrefByCancelledUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bookedFrom", nullable = false, length = 19)
	public Date getBookedFrom() {
		return this.bookedFrom;
	}

	public void setBookedFrom(Date bookedFrom) {
		this.bookedFrom = bookedFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bookedTo", nullable = false, length = 19)
	public Date getBookedTo() {
		return this.bookedTo;
	}

	public void setBookedTo(Date bookedTo) {
		this.bookedTo = bookedTo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bookedTime", nullable = false, length = 19)
	public Date getBookedTime() {
		return this.bookedTime;
	}

	public void setBookedTime(Date bookedTime) {
		this.bookedTime = bookedTime;
	}

	@Column(name = "seats")
	public Integer getSeats() {
		return this.seats;
	}

	public void setSeats(Integer seats) {
		this.seats = seats;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "totalPrice", nullable = false, precision = 22, scale = 0)
	public double getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(double totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "refundAmount", nullable = false, precision = 22, scale = 0)
	public double getRefundAmount() {
		return this.refundAmount;
	}

	public void setRefundAmount(double refundAmount) {
		this.refundAmount = refundAmount;
	}

	@Column(name = "paymentId", length = 45)
	public String getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(String paymentId) {
		this.paymentId = paymentId;
	}

	@Column(name = "refundId", length = 45)
	public String getRefundId() {
		return this.refundId;
	}

	public void setRefundId(String refundId) {
		this.refundId = refundId;
	}

	@Column(name = "paymentMethod", nullable = false, length = 10)
	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Column(name = "cancellationPolicyId", nullable = false)
	public int getCancellationPolicyId() {
		return this.cancellationPolicyId;
	}

	public void setCancellationPolicyId(int cancellationPolicyId) {
		this.cancellationPolicyId = cancellationPolicyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cancelledDateTime", nullable = false, length = 19)
	public Date getCancelledDateTime() {
		return this.cancelledDateTime;
	}

	public void setCancelledDateTime(Date cancelledDateTime) {
		this.cancelledDateTime = cancelledDateTime;
	}

	@Column(name = "bookingId", nullable = false)
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	@Column(name = "bookedStatus", nullable = false)
	public int getBookedStatus() {
		return this.bookedStatus;
	}

	public void setBookedStatus(int bookedStatus) {
		this.bookedStatus = bookedStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "approvedTime", length = 19)
	public Date getApprovedTime() {
		return this.approvedTime;
	}

	public void setApprovedTime(Date approvedTime) {
		this.approvedTime = approvedTime;
	}

}
