package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "huddil", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class City implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3774612757027530999L;
	private Integer id;
	private Tax tax;
	private String name;
	private List<Facility> facilities = new ArrayList<Facility>(0);
	private List<Location> locations = new ArrayList<Location>(0);
	private List<UserPref> userPrefs = new ArrayList<UserPref>(0);
	private List<Locality> localities = new ArrayList<Locality>(0);

	public City() {
	}

	public City(String name) {
		this.name = name;
	}

	public City(Tax tax, String name, List<Facility> facilities, List<Location> locations, List<UserPref> userPrefs,
			List<Locality> localities) {
		this.tax = tax;
		this.name = name;
		this.facilities = facilities;
		this.locations = locations;
		this.userPrefs = userPrefs;
		this.localities = localities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "taxId")
	@JsonProperty(access = Access.WRITE_ONLY)
	public Tax getTax() {
		return this.tax;
	}

	public void setTax(Tax tax) {
		this.tax = tax;
	}

	@Column(name = "name", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	@JsonIgnore
	public List<Facility> getFacilities() {
		return this.facilities;
	}

	public void setFacilities(List<Facility> facilities) {
		this.facilities = facilities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	@JsonIgnore
	public List<Location> getLocations() {
		return this.locations;
	}

	public void setLocations(List<Location> locations) {
		this.locations = locations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	@JsonIgnore
	public List<UserPref> getUserPrefs() {
		return this.userPrefs;
	}

	public void setUserPrefs(List<UserPref> userPrefs) {
		this.userPrefs = userPrefs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	@JsonIgnore
	public List<Locality> getLocalities() {
		return this.localities;
	}

	public void setLocalities(List<Locality> localities) {
		this.localities = localities;
	}

}
