package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Time;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * FacilityTiming generated by hbm2java
 */
@Entity
@Table(name = "facility_timing", catalog = "huddil")
public class FacilityTiming implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -808500921433514689L;
	private Integer id;
	private Facility facility;
	private int weekDay;
	private Time openingTime;
	private Time closingTime;

	public FacilityTiming() {
	}

	public FacilityTiming(Facility facility, int weekDay, Time openingTime, Time closingTime) {
		this.facility = facility;
		this.weekDay = weekDay;
		this.openingTime = openingTime;
		this.closingTime = closingTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "facilityId", nullable = false)
	@JsonIgnore
	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	@Column(name = "weekDay", nullable = false)
	public int getWeekDay() {
		return this.weekDay;
	}

	public void setWeekDay(int weekDay) {
		this.weekDay = weekDay;
	}

	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm")
	@Column(name = "openingTime", nullable = false, length = 8)
	public Time getOpeningTime() {
		return this.openingTime;
	}

	public void setOpeningTime(Time openingTime) {
		this.openingTime = openingTime;
	}

	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm")
	@Column(name = "closingTime", nullable = false, length = 8)
	public Time getClosingTime() {
		return this.closingTime;
	}

	public void setClosingTime(Time closingTime) {
		this.closingTime = closingTime;
	}

}
