package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * FacilityType generated by hbm2java
 */
@SqlResultSetMapping(name = "facilitystatus", classes = {
		@ConstructorResult(targetClass = StatusCount.class, columns = { @ColumnResult(name = "count"),
				@ColumnResult(name = "name") }) })
@Entity
@Table(name = "facility_type", catalog = "huddil", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class FacilityType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -956309955430735909L;
	private Integer id;
	private String name;
	private List<Facility> facilities = new ArrayList<Facility>(0);

	public FacilityType() {
	}

	public FacilityType(String name) {
		this.name = name;
	}

	public FacilityType(String name, List<Facility> facilities) {
		this.name = name;
		this.facilities = facilities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facilityType")
	@JsonIgnore
	public List<Facility> getFacilities() {
		return this.facilities;
	}

	public void setFacilities(List<Facility> facilities) {
		this.facilities = facilities;
	}

}
