package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * FacilityAdditionalCost generated by hbm2java
 */
@Entity
@Table(name = "facility_additional_cost", catalog = "huddil")
public class FacilityAdditionalCost implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1632391923778484734L;
	private int id;
	private Facility facility;
	private String name;
	private String description;
	private double price;

	public FacilityAdditionalCost() {
	}

	public FacilityAdditionalCost(int id, Facility facility, String name, double price) {
		this.id = id;
		this.facility = facility;
		this.name = name;
		this.price = price;
	}

	public FacilityAdditionalCost(int id, Facility facility, String name, String description, double price) {
		this.id = id;
		this.facility = facility;
		this.name = name;
		this.description = description;
		this.price = price;
	}

	public FacilityAdditionalCost(int i) {
		this.id = i;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "facilityId", nullable = false)
	@JsonProperty(access = Access.WRITE_ONLY)
	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 128)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
