package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * FacilityCancellationCharges generated by hbm2java
 */
@Entity
@Table(name = "facility_cancellation_charges", catalog = "huddil")
public class FacilityCancellationCharges implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2386954767618802214L;
	private Integer id;
	private int duration1;
	private double percentage1;
	private int duration2;
	private Double percentage2;
	private int duration3;
	private Double percentage3;
	private List<Booking> bookings = new ArrayList<Booking>(0);
	private List<Facility> facilities = new ArrayList<Facility>(0);

	public FacilityCancellationCharges() {
	}

	public FacilityCancellationCharges(int duration1, double percentage1) {
		this.duration1 = duration1;
		this.percentage1 = percentage1;
	}

	public FacilityCancellationCharges(int duration1, double percentage1, int duration2, Double percentage2,
			int duration3, Double percentage3, List<Booking> bookings, List<Facility> facilities) {
		this.duration1 = duration1;
		this.percentage1 = percentage1;
		this.duration2 = duration2;
		this.percentage2 = percentage2;
		this.duration3 = duration3;
		this.percentage3 = percentage3;
		this.bookings = bookings;
		this.facilities = facilities;
	}

	public FacilityCancellationCharges(int duration1, double percentage1, int duration2, double percentage2,
			int duration3, double percentage3) {
		this.duration1 = duration1;
		this.percentage1 = percentage1;
		this.duration2 = duration2;
		this.percentage2 = percentage2;
		this.duration3 = duration3;
		this.percentage3 = percentage3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "duration1", nullable = false)
	public int getDuration1() {
		return this.duration1;
	}

	public void setDuration1(int duration1) {
		this.duration1 = duration1;
	}

	@Column(name = "percentage1", nullable = false, precision = 22, scale = 0)
	public double getPercentage1() {
		return this.percentage1;
	}

	public void setPercentage1(double percentage1) {
		this.percentage1 = percentage1;
	}

	@Column(name = "duration2")
	public int getDuration2() {
		return this.duration2;
	}

	public void setDuration2(int duration2) {
		this.duration2 = duration2;
	}

	@Column(name = "percentage2", precision = 22, scale = 0)
	public Double getPercentage2() {
		return this.percentage2;
	}

	public void setPercentage2(Double percentage2) {
		this.percentage2 = percentage2;
	}

	@Column(name = "duration3")
	public int getDuration3() {
		return this.duration3;
	}

	public void setDuration3(int duration3) {
		this.duration3 = duration3;
	}

	@Column(name = "percentage3", precision = 22, scale = 0)
	public Double getPercentage3() {
		return this.percentage3;
	}

	public void setPercentage3(Double percentage3) {
		this.percentage3 = percentage3;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facilityCancellationCharges")
	@JsonIgnore
	public List<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(List<Booking> bookings) {
		this.bookings = bookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facilityCancellationCharges")
	@JsonIgnore
	public List<Facility> getFacilities() {
		return this.facilities;
	}

	public void setFacilities(List<Facility> facilities) {
		this.facilities = facilities;
	}

}
