package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * FacilityUnderMaintenance generated by hbm2java
 */
@SqlResultSetMapping(name = "facilityundermaintenance", classes = {
		@ConstructorResult(targetClass = FacilityUnderMaintenanceResult.class, columns = { @ColumnResult(name = "id"), @ColumnResult(name = "fromDateTime"),
				@ColumnResult(name = "toDateTime"), @ColumnResult(name = "reason"), @ColumnResult(name = "facilityId") }) })
@Entity
@Table(name = "facility_under_maintenance", catalog = "huddil")
public class FacilityUnderMaintenance implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1967186733535164953L;
	private Integer id;
	private Facility facility;
	private Date fromDateTime;
	private Date toDateTime;
	private String reason;

	public FacilityUnderMaintenance() {
	}

	public FacilityUnderMaintenance(Facility facility, Date fromDateTime, Date toDateTime) {
		this.facility = facility;
		this.fromDateTime = fromDateTime;
		this.toDateTime = toDateTime;
	}

	public FacilityUnderMaintenance(Facility facility, Date fromDateTime, Date toDateTime, String reason) {
		this.facility = facility;
		this.fromDateTime = fromDateTime;
		this.toDateTime = toDateTime;
		this.reason = reason;
	}

	public FacilityUnderMaintenance(int i) {
		this.id = i;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "facilityId", nullable = false)
	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
	@Temporal(TemporalType.DATE)
	@Column(name = "fromDateTime", nullable = false, length = 19)
	public Date getFromDateTime() {
		return this.fromDateTime;
	}

	public void setFromDateTime(Date fromDateTime) {
		this.fromDateTime = fromDateTime;
	}

	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
	@Temporal(TemporalType.DATE)
	@Column(name = "toDateTime", nullable = false, length = 19)
	public Date getToDateTime() {
		return this.toDateTime;
	}

	public void setToDateTime(Date toDateTime) {
		this.toDateTime = toDateTime;
	}

	@Column(name = "reason", length = 128)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
