package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * FacilityHistory generated by hbm2java
 */

@SqlResultSetMapping(name = "facilityHistory", classes = {
		@ConstructorResult(targetClass = FacilityHistory.class, columns = { @ColumnResult(name = "id"),
				@ColumnResult(name = "oldStatus"), @ColumnResult(name = "comments"), @ColumnResult(name = "facilityId"),
				@ColumnResult(name = "userId"), @ColumnResult(name = "dateTime") }) })

@Entity
@Table(name = "facility_history", catalog = "huddil")
public class FacilityHistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9171343668489902971L;
	private Integer id;
	private Facility facility;
	private Status status;
	private UserPref userPref;
	private String comments;
	private Date dateTime;
	private int oldStatus;
	private int facilityId;
	private int userId;

	public FacilityHistory() {
	}

	public FacilityHistory(Facility facility, Status status, UserPref userPref, Date dateTime) {
		this.facility = facility;
		this.status = status;
		this.userPref = userPref;
		this.dateTime = dateTime;
	}

	public FacilityHistory(Facility facility, Status status, UserPref userPref, String comments, Date dateTime) {
		this.facility = facility;
		this.status = status;
		this.userPref = userPref;
		this.comments = comments;
		this.dateTime = dateTime;
	}
	
	public FacilityHistory(int id, int oldStatus, String comments, int faciilityId, int userId, Date dateTime) {
		this.id = id;
		this.oldStatus = oldStatus;
		this.comments = comments;
		this.facilityId = faciilityId;
		this.userId = userId;
		this.dateTime = dateTime;
	}

	public FacilityHistory(int i) {
		this.id = i;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonProperty(access = Access.WRITE_ONLY)
	@JoinColumn(name = "facilityId", nullable = false)
	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oldStatus", nullable = false)
	@JsonProperty(access = Access.WRITE_ONLY)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonProperty(access = Access.WRITE_ONLY)
	@JoinColumn(name = "userId", nullable = false)
	public UserPref getUserPref() {
		return this.userPref;
	}

	public void setUserPref(UserPref userPref) {
		this.userPref = userPref;
	}

	@Column(name = "comments", length = 128)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy-MM-dd HH:mm:ss", timezone="GMT+5:30")
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateTime", nullable = false, length = 19)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Transient
	public int getOldStatus() {
		return this.oldStatus;
	}

	public void setOldStatus(int oldStatus) {
		this.oldStatus = oldStatus;
	}

	@Transient
	public int getFacilityId() {
		return facilityId;
	}

	public void setFacilityId(int facilityId) {
		this.facilityId = facilityId;
	}

	@Transient
	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}
}
