package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;

/**
 * Favorites generated by hbm2java
 */
@SqlResultSetMapping(name = "reports", classes = {
		@ConstructorResult(targetClass = PaymentReport.class, columns = { @ColumnResult(name = "date"),@ColumnResult(name = "title"),
				@ColumnResult(name = "facilityType"), @ColumnResult(name = "buildingName"), @ColumnResult(name = "city"),
				@ColumnResult(name = "locality"), @ColumnResult(name = "payment"), @ColumnResult(name = "consumerName"), @ColumnResult(name = "serviceProvider")}) })
@Entity
@Table(name = "favorites", catalog = "huddil")
public class Favorites implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6812086216771699910L;
	private Integer id;
	private Facility facility;
	private UserPref userPref;

	public Favorites() {
	}

	public Favorites(Facility facility, UserPref userPref) {
		this.facility = facility;
		this.userPref = userPref;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "facilityId", nullable = false)
	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public UserPref getUserPref() {
		return this.userPref;
	}

	public void setUserPref(UserPref userPref) {
		this.userPref = userPref;
	}

}
