package myapps.solutions.huddil.model;
// Generated Jan 30, 2018 11:50:26 AM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * LeastCost generated by hbm2java
 */
@Entity
@Table(name = "least_cost", catalog = "huddil", uniqueConstraints = @UniqueConstraint(columnNames = "typeName"))
public class LeastCost implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6857988033261636517L;
	private int id;
	private String typeName;
	private String cost;

	public LeastCost() {
	}

	public LeastCost(int id) {
		this.id = id;
	}

	public LeastCost(int id, String typeName, String cost) {
		this.id = id;
		this.typeName = typeName;
		this.cost = cost;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "typeName", unique = true, length = 45)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "cost", length = 45)
	public String getCost() {
		return this.cost;
	}

	public void setCost(String cost) {
		this.cost = cost;
	}

}
