package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Meeting generated by hbm2java
 */

@SqlResultSetMapping(name = "Meeting_View", classes = {
		@ConstructorResult(targetClass = MeetingResult.class, columns = { @ColumnResult(name = "id"),
				@ColumnResult(name = "title"), @ColumnResult(name = "description"),
				@ColumnResult(name = "participandsId"), @ColumnResult(name = "bookingId"),
				@ColumnResult(name = "fromTime"), @ColumnResult(name = "toTime"), @ColumnResult(name = "cityName"),
				@ColumnResult(name = "localityName"), @ColumnResult(name = "locationName"),
				@ColumnResult(name = "address"), @ColumnResult(name = "landmark"), @ColumnResult(name = "userId"),
				@ColumnResult(name = "displayName") }) })

@Entity
@Table(name = "meeting", catalog = "huddil")
public class Meeting implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3844962923690787726L;
	private Integer id;
	private Booking booking;
	private UserPref userPref;
	private String title;
	private String description;
	private String participandsId;

	public Meeting() {
	}

	public Meeting(int id) {
		this.id = id;
	}

	public Meeting(Booking booking, UserPref userPref, String title, String participandsId) {
		this.booking = booking;
		this.userPref = userPref;
		this.title = title;
		this.participandsId = participandsId;
	}

	public Meeting(Booking booking, UserPref userPref, String title, String description, String participandsId) {
		this.booking = booking;
		this.userPref = userPref;
		this.title = title;
		this.description = description;
		this.participandsId = participandsId;
	}

	public Meeting(int id, String title, String description, String participandsId, int userId, int bookingId) {
		this.id = id;
		this.title = title;
		this.description = description;
		this.participandsId = participandsId;
		// this.userPref = new UserPref(userId);
		this.booking = new Booking(id);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bookingId", nullable = false)
	public Booking getBooking() {
		return this.booking;
	}

	public void setBooking(Booking booking) {
		this.booking = booking;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	public UserPref getUserPref() {
		return this.userPref;
	}

	public void setUserPref(UserPref userPref) {
		this.userPref = userPref;
	}

	@Column(name = "title", nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 128)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@JsonProperty("teamId")
	@Column(name = "participandsId", nullable = false, length = 21000)
	public String getParticipandsId() {
		return this.participandsId;
	}

	public void setParticipandsId(String participandsId) {
		this.participandsId = participandsId;
	}

}
