package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;


/**
 * MultiTenant generated by hbm2java
 */
@Entity
@Table(name = "multi_tenant", catalog = "huddil")
public class MultiTenant implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5565600715971883510L;
	private Integer id;
	private UserPref userPref;
	private String title;
	private String emailId;
	private String description;
	private List<Location> locations = new ArrayList<Location>(0);
	private List<MutiTenantUser> mutiTenantUsers = new ArrayList<MutiTenantUser>(0);

	public MultiTenant() {
	}

	public MultiTenant(UserPref userPref) {
		this.userPref = userPref;
	}
	
	public MultiTenant(int id) {
		this.id = id;
	}

	public MultiTenant(UserPref userPref, String title, String emailId, String description, List<Location> locations,
			List<MutiTenantUser> mutiTenantUsers) {
		this.userPref = userPref;
		this.title = title;
		this.emailId = emailId;
		this.description = description;
		this.locations = locations;
		this.mutiTenantUsers = mutiTenantUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	@JsonProperty(access = Access.WRITE_ONLY)
	public UserPref getUserPref() {
		return this.userPref;
	}

	public void setUserPref(UserPref userPref) {
		this.userPref = userPref;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "emailId", length = 45)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "description", length = 21000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "multiTenant")
	@JsonIgnore
	public List<Location> getLocations() {
		return this.locations;
	}

	public void setLocations(List<Location> locations) {
		this.locations = locations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "multiTenant")
	@JsonIgnore
	public List<MutiTenantUser> getMutiTenantUsers() {
		return this.mutiTenantUsers;
	}

	public void setMutiTenantUsers(List<MutiTenantUser> mutiTenantUsers) {
		this.mutiTenantUsers = mutiTenantUsers;
	}

}
