package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MutiTenantUser generated by hbm2java
 */
@Entity
@Table(name = "muti_tenant_user", catalog = "huddil")
public class MutiTenantUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6924061947634775500L;
	private int userId;
	private MultiTenant multiTenant;

	public MutiTenantUser() {
	}

	public MutiTenantUser(int userId, MultiTenant multiTenant) {
		this.userId = userId;
		this.multiTenant = multiTenant;
	}

	@Id

	@Column(name = "userId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "muti_tenant_id", nullable = false)
	public MultiTenant getMultiTenant() {
		return this.multiTenant;
	}

	public void setMultiTenant(MultiTenant multiTenant) {
		this.multiTenant = multiTenant;
	}

}
