package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * ParticipantsTeam generated by hbm2java
 */

@SqlResultSetMapping(name = "team", classes = {
		@ConstructorResult(targetClass = ParticipantsTeam.class, columns = { @ColumnResult(name = "id"),
				@ColumnResult(name = "name"), @ColumnResult(name = "userId") }) })

@Entity
@Table(name = "participants_team", catalog = "huddil")
public class ParticipantsTeam implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3400830111822323616L;
	private Integer id;
	private UserPref userPref;
	private String name;
	private List<Participants> participantses = new ArrayList<Participants>(0);
	private int userId;

	public ParticipantsTeam() {
	}

	public ParticipantsTeam(int id) {
		this.id = id;
	}
	
	public ParticipantsTeam(UserPref userPref, String name) {
		this.userPref = userPref;
		this.name = name;
	}

	public ParticipantsTeam(UserPref userPref, String name, List<Participants> participantses) {
		this.userPref = userPref;
		this.name = name;
		this.participantses = participantses;
	}
	
	public ParticipantsTeam(int id, String name, int userId){
		this.id = id;
		this.userId = userId;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userId", nullable = false)
	@JsonProperty(access = Access.WRITE_ONLY)
	public UserPref getUserPref() {
		return this.userPref;
	}

	public void setUserPref(UserPref userPref) {
		this.userPref = userPref;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "participantsTeam")
	@JsonProperty(access = Access.WRITE_ONLY)
	public List<Participants> getParticipantses() {
		return this.participantses;
	}

	public void setParticipantses(List<Participants> participantses) {
		this.participantses = participantses;
	}

	@Transient
	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
