package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

/**
 * Participants generated by hbm2java
 */

@SqlResultSetMapping(name = "participants", classes = { @ConstructorResult(targetClass = Participants.class, columns = {
		@ColumnResult(name = "id"), @ColumnResult(name = "name"), @ColumnResult(name = "emailId"),
		@ColumnResult(name = "phoneNo"), @ColumnResult(name = "participantTeamId") }) })

@Entity
@Table(name = "participants", catalog = "huddil")
public class Participants implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2304581349588098783L;
	private Integer id;
	private ParticipantsTeam participantsTeam;
	private String name;
	private String emailId;
	private String phoneNo;
	private int participantTeamId;

	public Participants() {
	}

	public Participants(int id) {
		this.id = id;
	}

	public Participants(ParticipantsTeam participantsTeam, String name) {
		this.participantsTeam = participantsTeam;
		this.name = name;
	}

	public Participants(ParticipantsTeam participantsTeam, String name, String emailId, String phoneNo) {
		this.participantsTeam = participantsTeam;
		this.name = name;
		this.emailId = emailId;
		this.phoneNo = phoneNo;
	}

	public Participants(int id, String name, String emailId, String phoneNo, int ParticipantTeamId) {
		this.id = id;
		this.name = name;
		this.emailId = emailId;
		this.phoneNo = phoneNo;
		this.participantTeamId = ParticipantTeamId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "participantTeamId", nullable = false)
	@JsonProperty(access = Access.WRITE_ONLY)
	public ParticipantsTeam getParticipantsTeam() {
		return this.participantsTeam;
	}

	public void setParticipantsTeam(ParticipantsTeam participantsTeam) {
		this.participantsTeam = participantsTeam;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "emailId", length = 45)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "phoneNo", length = 45)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Transient
	public int getParticipantTeamId() {
		return participantTeamId;
	}

	public void setParticipantTeamId(int participantTeamId) {
		this.participantTeamId = participantTeamId;
	}
}
