package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.SqlResultSetMappings;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;



/**
 * Review generated by hbm2java
 */
@SqlResultSetMappings({
@SqlResultSetMapping(name = "reviewconsumer", classes = {
		@ConstructorResult(targetClass = ReviewResult.class, columns = { @ColumnResult(name = "id"),
				@ColumnResult(name = "comments"), @ColumnResult(name = "dateTime"), @ColumnResult(name = "rating"),
				@ColumnResult(name = "parentId"), @ColumnResult(name = "facilityId"),
				@ColumnResult(name = "bookingId") }) }),
@SqlResultSetMapping(name = "reviewRating", classes = {
		@ConstructorResult(targetClass = ReviewRating.class, columns = { @ColumnResult(name = "count"),
				@ColumnResult(name = "sum") }) }) })
@Entity
@Table(name = "review", catalog = "huddil")
public class Review implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8194099675448600243L;
	private Integer id;
	private int bookingHistory;
	private int facility;
	private Review review;
	private UserPref userPref;
	private String comments;
	private Date dateTime;
	private double rating;
	private List<Review> reviews = new ArrayList<Review>(0);

	public Review() {
	}

	public Review(int bookingHistory, int facility, UserPref userPref, Date dateTime, Integer rating) {
		this.bookingHistory = bookingHistory;
		this.facility = facility;
		this.userPref = userPref;
		this.dateTime = dateTime;
		this.rating = rating;
	}

	public Review(int bookingHistory, int facility, Review review, UserPref userPref, String comments, Date dateTime, Integer rating,
			List<Review> reviews) {
		this.bookingHistory = bookingHistory;
		this.facility = facility;
		this.review = review;
		this.userPref = userPref;
		this.comments = comments;
		this.dateTime = dateTime;
		this.rating = rating;
		this.reviews = reviews;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	/*@ManyToOne(fetch = FetchType.LAZY)
	@Join*/
	@Column(name = "bookingId", nullable = false)
	public int getBookingHistory() {
		return this.bookingHistory;
	}

	public void setBookingHistory(int bookingHistory) {
		this.bookingHistory = bookingHistory;
	}

	/*@ManyToOne(fetch = FetchType.LAZY)
	@Join*/
	@Column(name = "facilityId", nullable = false)
	@JsonIgnore
	public int getFacility() {
		return this.facility;
	}

	public void setFacility(int facility) {
		this.facility = facility;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parentId")
	@JsonIgnore
	public Review getReview() {
		return this.review;
	}

	public void setReview(Review review) {
		this.review = review;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "userId", nullable = false)
	public UserPref getUserPref() {
		return this.userPref;
	}

	public void setUserPref(UserPref userPref) {
		this.userPref = userPref;
	}

	@Column(name = "comments", length = 128)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	//@Temporal(TemporalType.DATE)
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+5:30")
	@Column(name = "dateTime", nullable = false, length = 19)
	public Date getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(Date dateTime) {
		this.dateTime = dateTime;
	}

	@Column(name = "rating", nullable = false)
	public double getRating() {
		return this.rating;
	}

	public void setRating(double rating) {
		this.rating = rating;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "review")
	public List<Review> getReviews() {
		return this.reviews;
	}

	public void setReviews(List<Review> reviews) {
		this.reviews = reviews;
	}

}
