package myapps.solutions.huddil.model;
// Generated Feb 20, 2018 11:51:07 AM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;

/**
* SpCommission generated by hbm2java
*/
@SqlResultSetMapping(name = "commissionDetails", classes = {
        @ConstructorResult(targetClass = CommissionDetails.class, columns = { @ColumnResult(name = "spuserId"),
                @ColumnResult(name = "currentMonthCommission"), @ColumnResult(name = "nextMonthCommission") }) })
@Entity
@Table(name = "sp_commission", catalog = "huddil")
public class SpCommission implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -7364075313008281784L;
	private Integer id;
    private UserPref userPref;
    private String month;
    private String year;
    private double commission;

    public SpCommission() {
    }

    public SpCommission(UserPref userPref, String month, String year, double commission) {
        this.userPref = userPref;
        this.month = month;
        this.year = year;
        this.commission = commission;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "spUserId", nullable = false)
    public UserPref getUserPref() {
        return this.userPref;
    }

    public void setUserPref(UserPref userPref) {
        this.userPref = userPref;
    }

    @Column(name = "month", nullable = false, length = 16777215)
    public String getMonth() {
        return this.month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    @Column(name = "year", nullable = false, length = 45)
    public String getYear() {
        return this.year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    @Column(name = "commission", nullable = false, precision = 22, scale = 0)
    public double getCommission() {
        return this.commission;
    }

    public void setCommission(double commission) {
        this.commission = commission;
    }

}