package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "huddil", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Status implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4246953429954722659L;
	private Integer id;
	private String name;
	private List<FacilityHistory> facilityHistories = new ArrayList<FacilityHistory>(0);

	public Status() {
	}

	public Status(int id) {
		this.id = id;
	}

	public Status(String name) {
		this.name = name;
	}

	public Status(String name, List<FacilityHistory> facilityHistories) {
		this.name = name;
		this.facilityHistories = facilityHistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public List<FacilityHistory> getFacilityHistories() {
		return this.facilityHistories;
	}

	public void setFacilityHistories(List<FacilityHistory> facilityHistories) {
		this.facilityHistories = facilityHistories;
	}

}
