package myapps.solutions.huddil.model;
// Generated Nov 24, 2017 1:13:20 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tax generated by hbm2java
 */
@Entity
@Table(name = "tax", catalog = "huddil")
public class Tax implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7320262050352894937L;
	private Integer id;
	private String state;
	private double sgst;
	private double cgst;
	private Double igst;
	private Set<City> cities = new HashSet<City>(0);

	public Tax() {
	}

	public Tax(String state, double sgst, double cgst) {
		this.state = state;
		this.sgst = sgst;
		this.cgst = cgst;
	}

	public Tax(String state, double sgst, double cgst, Double igst, Set<City> cities) {
		this.state = state;
		this.sgst = sgst;
		this.cgst = cgst;
		this.igst = igst;
		this.cities = cities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "state", nullable = false, length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "SGST", nullable = false, precision = 22, scale = 0)
	public double getSgst() {
		return this.sgst;
	}

	public void setSgst(double sgst) {
		this.sgst = sgst;
	}

	@Column(name = "CGST", nullable = false, precision = 22, scale = 0)
	public double getCgst() {
		return this.cgst;
	}

	public void setCgst(double cgst) {
		this.cgst = cgst;
	}

	@Column(name = "IGST", precision = 22, scale = 0)
	public Double getIgst() {
		return this.igst;
	}

	public void setIgst(Double igst) {
		this.igst = igst;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tax")
	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

}
