package myapps.solutions.huddil.model;
// Generated Nov 17, 2017 4:19:00 PM by Hibernate Tools 5.2.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserType generated by hbm2java
 */
@Entity
@Table(name = "user_type", catalog = "huddil", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class UserType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7724210954414094284L;
	private Integer id;
	private String name;
	private List<UserPref> userPrefs = new ArrayList<UserPref>(0);

	public UserType() {
	}

	public UserType(String name) {
		this.name = name;
	}

	public UserType(String name, List<UserPref> userPrefs) {
		this.name = name;
		this.userPrefs = userPrefs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userType")
	public List<UserPref> getUserPrefs() {
		return this.userPrefs;
	}

	public void setUserPrefs(List<UserPref> userPrefs) {
		this.userPrefs = userPrefs;
	}

}
